# Use the official Python image as the base
# -- check https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html 
# -- or https://docs.nvidia.com/deeplearning/frameworks/pdf/PyTorch-Release-Notes.pdf -> 23.01 (python 3.8, cuda12.0.1)
# FROM nvcr.io/nvidia/pytorch:23.01-py3
FROM python:3.10-slim
# FROM python:3.10-buster

# Set working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install system dependencies
RUN apt-get update && apt-get install -y nano curl
RUN apt update && apt install -y ffmpeg curl && apt clean


RUN apt-get update && apt-get install -y \
    nano \
    curl \
    git \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgl1 \
    poppler-utils \
    gcc \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add TMUX 
RUN apt-get update && \
    apt-get install -y tmux && \
    rm -rf /var/lib/apt/lists/*

# Set locale
# RUN locale-gen en_US.UTF-8
# ENV LANG en_US.UTF-8
# ENV LANGUAGE en_US:en
# ENV LC_ALL en_US.UTF-8

# Install Python dependencies (use requirements.txt to manage them)
RUN pip install --no-cache-dir -r requirements.txt

# Expose port (change if your app uses another port)
# EXPOSE 5000

# Set the command to run the app (modify as needed)
# CMD ["python", "app.py"]

WORKDIR /home